Models/DataModel/ImageModel.cs
namespace KammalKada.Models.DataModel
{
	public class ImageModel
	{
		public string Name { get; set; }
		public string Path { get; set; }
	}
}

Models/DataModel/UserDM.cs
namespace KammalKada.Models.DataModel
{
	public class UserDM
	{
		public int EmployeeId { get; set; }
		public string EmployeeName { get; set; }
		public string EmailId { get; set; }
		public string PhoneNumber { get; set; }
	}
}

Models/ErrorViewModel.cs
namespace KammalKada.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace KammalKada.Models
{
	public class LoginViewModel
	{
		[Required]
		public string Username {  get; set; }
		[Required]
		public string Password { get; set; }
	}
}

Controllers/HomeController.cs
using System.Diagnostics;
using KammalKada.Models;
using KammalKada.Models.DataModel;
using Microsoft.AspNetCore.Mvc;

namespace KammalKada.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly string contactNumber;

        public HomeController(ILogger<HomeController> logger, IConfiguration configuration)
        {
            _logger = logger;
            contactNumber = configuration["WhatsappContact:ContactNum"];
        }

        public IActionResult Index()
        {
            ViewBag.contactNumber = contactNumber;
            return View();
        }

		public IActionResult OverView()
		{
			var images = new List<ImageModel>
			{
				new ImageModel { Name="Diamond Bangle",Path=Url.Content("~/Images/Diamond_bangle_for_Girls.jpg") },
				new ImageModel { Name="Diamond Earrings",Path=Url.Content("~/Images/Diamond_Earrings.jpg") },
				new ImageModel { Name="Diamond Necklace",Path=Url.Content("~/Images/Diamond_Necklace.png") },
				new ImageModel { Name="Diamond Ring",Path=Url.Content("~/Images/Diamond_Ring.jpg") },
				new ImageModel { Name="Gold Bracelet",Path=Url.Content("~/Images/Gold_Bracelet.jpg") },
				new ImageModel { Name="Gold Earrings",Path=Url.Content("~/Images/Gold_Earrings.jpg") },
				new ImageModel { Name="Gold Ring",Path=Url.Content("~/Images/Gold_Ring.jpg") },
				new ImageModel { Name="Gold Ring Men",Path=Url.Content("~/Images/Gold_Ring_Men.jpg") },
				new ImageModel { Name="Diamond Bangle",Path=Url.Content("~/Images/Platinum_Diamond_Bangle.jpg") },
				new ImageModel { Name="Diamond Bangle",Path=Url.Content("~/Images/Diamond_Bangle.jpg") }
			};
			return PartialView("_overview", images);
		}

        public IActionResult Cart()
        {
            return View();
        }
		public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using KammalKada.Models.DataModel;

namespace KammalKada.Controllers
{
	public class ProductController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Controllers/SecurityController.cs
using KammalKada.Models;
using KammalKada.Models.DataModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using System.Text;

namespace KammalKada.Controllers
{
	public class SecurityController : Controller
	{
		private readonly HttpClient httpClient;
		private readonly string baseurl;
		public SecurityController(IConfiguration configuration)
		{
			baseurl = configuration["ApiSettings:baseUrl"];
			httpClient = new HttpClient
			{
				BaseAddress = new Uri(baseurl)
			};
		}
		// GET: SecurityController
		public ActionResult Index()
		{
			return View();
		}

		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
			return RedirectToAction("Index", "Home");
		}

		public async Task<IActionResult> Login( LoginViewModel model)
		{
			try
			{
				if (!ModelState.IsValid)
				{
					return RedirectToAction("Error", "Home");
				}

				var logindata = new
				{
					Email = model.Username,
					Password = model.Password
				};

				var claim = new List<Claim>
				{
					new Claim(ClaimTypes.Name, model.Username),
					//new Claim(ClaimTypes.Email, user.EmailId),
					//new Claim(ClaimTypes.MobilePhone, user.PhoneNumber)
				};

				var identity = new ClaimsIdentity(claim, CookieAuthenticationDefaults.AuthenticationScheme);
				var principal = new ClaimsPrincipal(identity);

				await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

				return RedirectToAction("Index", "Home");

				//var data = new StringContent(
				//	System.Text.Json.JsonSerializer.Serialize(logindata),
				//	Encoding.UTF8,
				//	"application/json");

				//HttpResponseMessage response = await httpClient.PostAsync("/api/Employee/login", data);
				//if (response.IsSuccessStatusCode)
				//{
				//	var user = await response.Content.ReadFromJsonAsync<UserDM>();
				//	var claim = new List<Claim>
				//{
				//	new Claim(ClaimTypes.Name, user.EmployeeName),
				//	new Claim(ClaimTypes.Email, user.EmailId),
				//	new Claim(ClaimTypes.MobilePhone, user.PhoneNumber)
				//};

				//	var identity = new ClaimsIdentity(claim, CookieAuthenticationDefaults.AuthenticationScheme);
				//	var principal = new ClaimsPrincipal(identity);

				//	await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

				//	return RedirectToAction("Index", "Home");
				//}

				//return View();
			}
			catch(Exception ex)
			{
				return RedirectToAction("Error", "Home");
			}
			
		}

		// GET: SecurityController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: SecurityController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: SecurityController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: SecurityController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: SecurityController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: SecurityController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: SecurityController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

Views/Home/Index.cshtml
@model IEnumerable<KammalKada.Models.DataModel.ImageModel>;
@{
    ViewData["Title"] = "Home Page";
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" rel="stylesheet" asp-append-version="true" />
<link rel="stylesheet" href="~/css/KammalKada.css" asp-append-version="true" />
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="~/Scripts/KammalKada.js" asp-append-version="true"></script>

<div class="text-center">
    <div style="background-color:#5E3A3F;width:50px;height:50px;border-radius:50%;align-content:center;z-index:1000;position:fixed;bottom:40px;right:40px">
        <i id = "whatsappChatIcon" class="fab fa-whatsapp" style="font-size:40px;color:white;"></i>
    </div>
    <div id="imageCarousel" class="carousel carousel-fade" data-ride="carousel" data-interval="2000" data-pause="hover">

        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#imageCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#imageCarousel" data-slide-to="1"></li>
            <li data-target="#imageCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Carousel images -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Images/Diamond_bangle_for_Girls.jpg" class="d-block w-100" alt="Image 1">
            </div>
            <div class="carousel-item">
                <img src="~/Images/Diamond_Earrings.jpg" class="d-block w-100" alt="Image 2" />
            </div>
            <div class="carousel-item">
                <img src="~/Images/Platinum_Diamond_Bangle.jpg" class="d-block w-100" alt="Image 3">
            </div>
		</div>

        <!-- Controls -->
        @* <a class="carousel-control-prev" href="#imageCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#imageCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a> *@
    </div>

    <div id="itemsContainer" style="margin-top:30px;margin-right:0px;height:auto;overflow-x:scroll;overflow-y:hidden;">

    </div>

    <div id="overviewContainer" style="margin-top:30px;margin-right:0px;height:auto;overflow-x:scroll;overflow-y:hidden;">
        @* @Html.PartialAsync("_overview", Model); *@
        @* @Html.Partial("~/Views/Products/_overview.cshtml") *@
    </div>

    <div class="container" id="container-chat">
        <div id="chatwindow" style="display:none; position:fixed;bottom:100px;right:40px;
            width:20vw;min-width:300px; height:auto; background:none; z-index:1000;border-color:#5E3A3F;border-style:solid;border-radius:10px;">

            <div id="popupBox" style="background:#CCAEB1; padding:10px; border-radius:10px;min-width:300px;
                width:20vw; height:auto; text-align:center; position:relative; box-shadow:0 4px 10px rgba(0,0,0,0.3);">
                <div id="close1" style="display:flex;justify-self:end; align-items:center; color:white;
                     width:20px;height:20px;background:#5E3A3F;cursor:pointer;border-radius:50%;">
                    <i class="fa fa-close"></i>
                </div>
                <div id="modal-body" style="display:flex;flex-direction:column;justify-content:center;margin:20px">
                    <h6 style="align-self:flex-start;">Hi! How can I Help You?</h6>
                    <textarea id="querybox" style="border: 2px solid #5E3A3F; border-radius: 5px;min-height:100px;" placeholder="Enter your query here!!"></textarea>
                    <button id="btnSend" style="margin-top:20px;border: 2px solid #5E3A3F;color:white; background-color:#5E3A3F; border-radius: 5px;" type="submit">Send</button>
                </div>
            </div>
        </div>
    </div>
    
@section Scripts {
    <script>
        var contactNumber = '@ViewBag.contactNumber';
    </script>

        @* <script src="~/Scripts/KammalKada.js" asp-append-version="true"></script> *@
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    @* <script>
        $(function () {
            // Load partial from Home/OverView
            $("#overviewContainer").load("/Home/OverView");
        });
    </script> *@
}

Views/Home/_overview.cshtml
@model IEnumerable<KammalKada.Models.DataModel.ImageModel>;

<div style="margin:10px;display:flex;flex-direction:row;gap:20px;justify-content:flex-start;">
	@foreach(var img in Model){
		<div class="card">
			<div class="card-image" style="cursor:pointer;">
				<img src="@img.Path" alt="@img.Name">
			</div>
			<div class="card-content" style="display:flex;flex-direction:row;justify-content:space-between;">
				<div style="display:flex;justify-self:start;flex-direction:column;align-items:start;">
					@* <div style="display:flex;flex-direction:row;">
						@for (int j = 0; j < 5; j++)
						{
							<i id="ratingIcon" style="cursor:pointer;font-size:25px;" class="far fa-star"></i>
						}
					</div> *@
					<p style="font-weight:bold;font-size:15px">@img.Name</p>
				</div>
				<div class="btnAddDiv" style="display:flex;justify-self:end;flex-direction:column;justify-content: center;align-items:center;margin-bottom:10px; ">
					<button type="button" class="btnAdd">Add to Cart</button>
				</div>
				<div class="btnCountDiv" style="display:none;justify-self:end;flex-direction:row;justify-content:flex-end; align-items:center; margin-bottom:10px; ">
					<button type="button" class="card-btn btnMinus" style="width:40px;height:40px;border-radius:50%;align-content:center;font-size:20px;"><i class="fa-solid fa-minus"></i></button>
					<span class="count" style="font-size:20px"></span>
					<button type="button" class="card-btn btnPlus" style="width:40px;height:40px;border-radius:50%;align-content:center; font-size:20px;"><i class="fa-solid fa-plus"></i></button>
				</div>
			</div>
		</div>
	}
	

	@* <div style="width:400px;height:400px;border:thick">
		<img style="width:300px;height:300px;" src="~/Images/discountBanner.png" alt="Alternate Text" />
		<div style="width:100%;height:100px;">
			<p>Rs. 500</p>
			<p>*****</p>
		</div>
	</div>
	<div style="width:400px;height:400px;border:thick">
		<img style="width:300px;height:300px;" src="~/Images/discountBanner.png" alt="Alternate Text" />
		<div style="width:100%;height:100px;">
			<p>Rs. 500</p>
			<p>*****</p>
		</div>
	</div>
	<div style="width:400px;height:400px;border:thick">
		<img style="width:300px;height:300px;" src="~/Images/discountBanner.png" alt="Alternate Text" />
		<div style="width:100%;height:100px;">
			<p>Rs. 500</p>
			<p>*****</p>
		</div>
	</div>
	<div style="width:400px;height:400px;border:thick">
		<img style="width:300px;height:300px;" src="~/Images/discountBanner.png" alt="Alternate Text" />
		<div style="width:100%;height:100px;">
			<p>Rs. 500</p>
			<p>*****</p>
		</div>
	</div>
	<div style="width:400px;height:400px;border:thick">
		<img style="width:300px;height:300px;" src="~/Images/discountBanner.png" alt="Alternate Text" />
		<div style="width:100%;height:100px;">
			<p>Rs. 500</p>
			<p>*****</p>
		</div>
	</div>
	<div style="width:400px;height:400px;border:thick">
		<img style="width:300px;height:300px;" src="~/Images/discountBanner.png" alt="Alternate Text" />
		<div style="width:100%;height:100px;">
			<p>Rs. 500</p>
			<p>*****</p>
		</div>
	</div> *@
</div>

Views/Security/_login.cshtml
@model KammalKada.Models.LoginViewModel

<div class="p-3" >
    <h1 style="font-size:30px; justify-self: start; margin-left:20px;">Login</h1>
    @using (Html.BeginForm("Login", "Security", FormMethod.Post, new { id = "loginForm" }))
    {
        <div class=" input-items">
            @Html.TextBoxFor(m => m.Username, new { @class = "input-fields ", placeholder="Username" })
        </div>
        <div class="form-group input-items">
            @Html.PasswordFor(m => m.Password, new { @class = "input-fields ", placeholder = "Password" })
        </div>
        <div>
            <a style="font-size:10px;justify-self:end; padding:10px" asp-controller="Home" asp-action="Index">New User?</a>
        </div>
        <div>
            <button type="submit" class="input-items loginBtn">Login</button>
        </div>
        
        @* <button type="button" id="btnRegister" class="btn btn-secondary input-items" style="background-color:#5E3A3F; border:none;">Register</button> *@
    }
</div>

Views/Security/_register.cshtml
<div style="border:1px solid #ccc; padding:10px; margin-top:10px;">
    <h3>Register</h3>
    @Html.Label("name","Name")
    @Html.TextBox("name")
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KammalKada</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KammalKada.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/KammalKada.css" asp-append-version="true"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <header style="background-color:#5E3A3F;">
        <div class="marqueeDiv">
            <marquee>Free Delivery for selected items...</marquee>
        </div>
        <nav id="nav" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">@* bg-white *@
            <div id="nav" class="container-fluid">
                <button class="navbar-toggler" style="border-color:white;background-color:#76484D" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <img src="~/Images/menu.svg" role="button" style="width:30px;height:30px" alt="Menu" />
                    @* <span class="navbar-toggler-icon" style="color:white !important;"></span> *@
                </button>
                <a class="navbar-brand header__logo" style="font-family:Mistral;font-size:40px;color:white;margin-left:auto;" asp-area="" asp-controller="Home" asp-action="Index">Kammal Kada</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-item-text text-dark" asp-area="" asp-controller="Home" asp-action="Index">Crazy Deals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item-text text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">
                                Clearance Sale 🔥
                            </a>
                        </li>
                        <li class="dropdown ">
                            <a class="dropdown-toggle nav-item-text" href="#" id="earringsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Earrings
                            </a>
                            <ul class="dropdown-menu dropdown-style" style="display:none;" aria-labelledby="earringsDropdown" id="dropdownlist">
                                <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Studs">Studs</a></li>
                                <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Jhumka">Jhumka</a></li>
                                <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Danglers">Danglers</a></li>
                                <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Studs">Studs</a></li>
                                <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Jhumka">Jhumka</a></li>
                                <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Danglers">Danglers</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item-text text-dark" asp-area="" asp-controller="Home" asp-action="Index">Rings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item-text text-dark" asp-area="" asp-controller="Home" asp-action="Index">Bracelet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item-text text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accessories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item-text text-dark" asp-area="" asp-controller="Home" asp-action="Index">New Arrivals</a>
                        </li>
                    </ul>
                </div>
                <div class="d-flex">
                    <ul class="navbar-nav flex-grow-1" style="display:flex;flex-direction:row; margin:auto">
                        <li class="nav-item" style="margin-right:20px;">
                            <a asp-controller="Home" asp-action="Cart">
                                <img src="~/Images/Cart.svg" role="button" style="width:40px;height:40px" alt="Cart" />
                            </a>
                        </li>
                        <li class="nav-item">
                            @if(User.Identity.IsAuthenticated)
                            {
                                <li class="dropdown" style="margin-right:40px;">
                                    <a class=" nav-item-text" href="#" id="userProfile" style="font-size:20px;font-weight:bold;" role="button" data-bs-toggle="dropdown" aria-expanded="false" >Welcome! @User.Identity.Name</a>
                                    <ul class="dropdown-menu dropdown-style" aria-labelledby="userProfile" id="dropdownlist1" style="z-index:2000;opacity:1;display:none;">
                                        <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Index">Profile</a></li>
                                        <li><a class="dropdown-item items" asp-area="" asp-controller="Home" asp-action="Index">Settings</a></li>
                                        <li><a class="dropdown-item items" asp-area="" asp-controller="Security" asp-action="Logout">Logout</a></li>
                                    </ul>
                                </li>
                                
                            }
                            else
                            {
                                <a id="login">
                                    <img src="~/Images/User.svg" role="button" style="width:40px;height:40px;margin-right:40px;" alt="User" />
                                </a>
                            }
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" id="container-all">
        @* <div id="modal">
            <button id="close">close</button>
            Hi How Are You?
        </div> *@
        @* <div id="modal" style="display:none; position:fixed; top:0; left:0; width:100%; height:100%;
                background:rgba(0,0,0,0.5); justify-content:center; align-items:center; z-index:1000;">

            <div id="popupBox" style="background:#fff; padding:20px; border-radius:10px; width:300px; text-align:center; position:relative;">
                <h3>Popup Title</h3>
                <p>This is a simple popup message.</p>
                <button id="close" style="margin-top:10px;">Close</button>
            </div>
        </div> *@
        <div id="modal" style="display:none; position:fixed; top:130px; right:20px;
            width:auto; height:auto; background:none; z-index:1000;border-color:#5E3A3F;border-style:solid;border-radius:10px;">

            <div id="popupBox" style="background:#CCAEB1; padding:10px; border-radius:10px;
                width:100%; height:auto; text-align:center; position:relative; box-shadow:0 4px 10px rgba(0,0,0,0.3);">
                <div id="close" style="display:flex;justify-self:end; align-items:center; color:white;
                     width:20px;height:20px;background:#5E3A3F;cursor:pointer;border-radius:50%;">
                    <i class="fa fa-close"></i>
                </div>
                <div id="modal-body">

                </div>
            </div>
        </div>

        <main role="main" class="pb-3" style="width:100%;">
            @RenderBody()
        </main>
    </div>
    <div id="loginContent" style="display:none;">
        @Html.Partial("~/Views/Security/_login.cshtml")
    </div>

    <div id="registerContent" style="display:none;">
        @Html.Partial("~/Views/Security/_register.cshtml")
    </div>

    <footer class="border-top footer text-muted" style="background-color:#5E3A3F;">
        <div class="container">
            &copy; 2025 - with love from KammalKada - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/Scripts/KammalKada.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>